language: ruby
rvm:
  - 2.4.1
env:
  - TWINX_DB_USER=postgres
addons:
    firefox: "47.0.1"
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
script:
  - RAILS_ENV=test bundle exec rake db:migrate test
  - RAILS_ENV=test bundle exec rspec
before_script:
  - psql -c 'create database twinx_test;' -U postgres
cache: bundler
sudo: false
