defaults: &defaults
  adapter: postgresql
  encoding: unicode
  pool: 20
  username: <%= ENV['TWINX_DB_USER'] %>
  password:

development:
  <<: *defaults
  database: twinx_development

test:
  <<: *defaults
  database: twinx_test

production:
  <<: *defaults
  database: twinx_production
